### ISSUE TITLE
Suggestion: add required version of node.js

### ISSUE THREAD

**Issue by fengh16** [AI4Organization/DALL-E-3-WebUI#26]
Since Next.js is used here, the node version should be at least 18.X . ( Some discussions here: https://github.com/vercel/next.js/discussions/47648 ) So I suggest you to put this requirement in readme.md.

**Comment by KennyDizi** [comment]
thanks @fengh16, I will update it soon.

**Comment by KennyDizi** [comment]
closed via https://github.com/AI4Organization/DALL-E-3-WebUI/pull/27
